version: "3.9"

services:
  backend:
    build: 
      context: ./Back-End
      dockerfile: be.dockerfile
    container_name: crowd-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      USER: postgres
      PASSWORD: test1234
      HOST: db.fagpgmsjmthankkiuqaq.supabase.co
      PORT: 5432
      DATABASE: postgres
    restart: always

  frontend:
    build:
      context: ./Front-End
      dockerfile: fe.dockerfile
    container_name: crowd-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
